from enum import Enum

class Leagues(Enum):
   Nba = "NBA"
   NbaMvp = "NBA_MVP"
   NbaShowdown = "NBA_SHOWDOWN"
   Wnba = "WNBA"
   Nfl = "NFL"
   NflMvp = "NFL_MVP"
   NflShowdown = "NFL_SHOWDOWN"
   Pga = "PGA"
   PgaCaptain = "PGA_CAPTAIN"
   Nascar = "NASCAR"
   Mlb = "MLB"
   MlbMvp = "MLB_MVP"
   MlbShowdown = "MLB_SHOWDOWN"
   Soccer = "SOCCER"
   El = "EL"
   Nhl = "NHL"
   NhlShowdown = "NHL_SHOWDOWN"
   Xfl = "XFL"
   Ten = "TEN"
   CsgoShowdown = "CSGO_SHOWDOWN"
   F1Showdown = "F1_SHOWDOWN"